### ISSUE TITLE
realizar mockups web de avances

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#1]
para realizar los mockups se comparte el enlace de:

- [el acta de la reunión donde se realizo la primera explicacion](https://drive.google.com/drive/folders/1GJ-0mBMACsrBp48x-u5KIKTU2mjh1TLq?usp=sharing)
- [la carpeta de mockup e historias de usuario](https://drive.google.com/drive/folders/1CTxjnMVa4PA2ZDjci2LACthHrinln0YW?usp=sharing). Dentro de ese enlace los archivos de internes son:
  - los mockups que se encontraran en la siguiente ruta  `parte gráfica de usuario > avances > parte grafica avances v2.pdf`
  - historias de usuario en la ruta: `HU- versión 3 > avances`

**Comment by dmarcela09** [comment]
Se crean los mockups en el siguiente enlace https://drive.google.com/file/d/1ZdgZttbfQlE0mfuFAUvYQTEJd3nRlmFG/view?usp=sharing

**Comment by BOTOOM** [comment]
revisando según las historias de usuario en la creación de tipo de avance te hace falta el atributo de `link de la norma`

para consulta de avances se requiere consultar por el tercero, así que falta el tipo de documento y el numero de documento del tercero

**Comment by BOTOOM** [comment]
en legalización/reintegro en el paso 1 cambia de lugar el input del recibo de caja y el boton de consultar ingreso ya que supongo que el ingreso se consultara según el recibo de caja

en legalización del avance en la parte de los estudiantes , para la columna de firma , coloca una nota, donde se dice que ese campo no ha de ser necesario, jajaajaj por que ni idea como cargaremos la firma de un estudiante a una tabla jajaaja

de los mokups elimina el consecutivo y la fecha, eso sera algo generado automáticamente, de las tablas no pero de los formularios si

en legalización de avances y en reintegros donde se busca la orden de pago, no usamos la fecha para la búsqueda, usamos la vigencia, así que si aparece la fecha quilata y deja la vigencia, no tiene sentido dejar la fecha

en reintegros el numero del cdp y crp no se digita, ya se trea por ende estos campos no son de escribir

en reintegro, conde dice concepto, si no estoy mal ,alli debe haber un select o auto completado para consultar el concepto a usar
