### ISSUE TITLE
Realizar vista de legalización avance(incluye normal y practicas académicas)

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#14]

**Comment by Jeisson005** [comment]
Se crean las siguientes vistas:
http://localhost:4200/#/pages/avances/legalizacionavance/lista
![image](https://user-images.githubusercontent.com/24659130/108557844-203f2680-72c7-11eb-8f46-e50749c10d86.png)

http://localhost:4200/#/pages/avances/legalizacionavance/crear
![image](https://user-images.githubusercontent.com/24659130/108558086-6bf1d000-72c7-11eb-8a66-ecbca086b517.png)
![image](https://user-images.githubusercontent.com/24659130/108558116-7744fb80-72c7-11eb-88d6-10ba37510449.png)
![image](https://user-images.githubusercontent.com/24659130/108558323-c1c67800-72c7-11eb-9a84-619beb6c9fbd.png)
