### ISSUE TITLE
mockups inversiones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#16]
se requiere realizar los mockups de ingresos, para el sistema de tesorería.

- [carpeta con acta y grabación](https://drive.google.com/drive/folders/1Q-d7GSgYEsI2Kyj2R6Zb-XZRB7-UVpUJ?usp=sharing)

**Comment by dmarcela09** [comment]
El enlace a los mockups realizados para Inversiones es https://drive.google.com/file/d/1rIobCKwnDy-fGj0YOopOtyEC_YFRvfzQ/view?usp=sharing
