### ISSUE TITLE
socializacion mokups bancos y cheques

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#17]
se ha de realizar la socializacion de los mockups de bancos y cheques

**Comment by Jeisson005** [comment]
Se realizan los siguientes ajustes a los mockups según lo acordado en la reunión, se encuentran en el siguiente [Enlace](https://drive.google.com/file/d/1kkj94huSsMuUmTCtfozOG6lwpuDyFobJ/view?usp=sharing)

- [x] Se agrega el mockup de vistas de gestión Sucursales

- [x] Se agregan los datos presupuestales de la orden de pago a la vista de giro del cheque (CDP, RP y rubro presupuestal)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
