### ISSUE TITLE
socialización de mockups de giros

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#23]
se require realiza la socializacion de los mockups de giros los cuales se encuentran en el issue #4

**Comment by Miranda13** [comment]
Se socializa con @mcrubianot los Mockups de giros: giros a proveedores, pago de nómina por relación de autorización, pago de seguridad social, radicación de orden de pago y relación de autorización y reversar giro. Los ajustes que se deben hacer son los siguientes:

[ ] Agregar en los atributos de las tablas de relación de autorización nombre y número de documento.
[ ] Agregar en todos los modelos tipo de comprobante, código y consecutivo como select.
[ ] Elegir órdenes de pago a través de un rango.
[ ] Cambiar nombre de la cuenta bancaria por un select.
[ ] Agregar justificación para retirar órdenes de pago a girar.
[ ] En erogación del giro agregar los datos del tercero.
[ ] En giros de relación de autorización los rubros mostrarlos como una lista con código, nombre y valor.

**Comment by Miranda13** [comment]
@mcrubianot informa el día 16 de abril que los mockups de giros fueron aprobados por el usuario sin observaciones
