### ISSUE TITLE
crear vista de bancos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#24]
con base en los mockups #3 se requiere realizar la vista de bancos.

***Nota: primero se debe crear un modulo de giros que contendra este modulo y todos los que tengan que ver con giros***

**Comment by Jeisson005** [comment]
![image](https://user-images.githubusercontent.com/24659130/108560492-cd676e00-72ca-11eb-9e67-eeb67cbd40de.png)

![image](https://user-images.githubusercontent.com/24659130/108561026-8fb71500-72cb-11eb-84bf-9ce78a936f64.png)
