### ISSUE TITLE
realizar mockups de bancos y cheques 

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#3]
en base a [parte grafica de bancos y cheques](https://drive.google.com/drive/folders/1J_m9Uhu0QKOHWR_TIetwcvC_MrMF6pbZ?usp=sharing) y en los videos realizados del giros que comprenden inicialmente bancos y cheques se requiere realizar los mokups de bancos y cheques.

--- 
videos:
- [primera sesion](https://drive.google.com/drive/folders/1ngEpvmpFgt5ZxCBZFeYrXx_Axn37XIGv?usp=sharing)
- [segunda sesion](https://drive.google.com/drive/folders/1-CrweOYU9A0Dsf8WRKHApr7IKby5TuAq?usp=sharing)

---

***nota se compartira por correo docuentos relacionados de desarrollos anteriores***

**Comment by Jeisson005** [comment]
Se crean los mockups, están en el siguiente (Enlace)[https://drive.google.com/file/d/1kkj94huSsMuUmTCtfozOG6lwpuDyFobJ/view?usp=sharing]

**Comment by BOTOOM** [comment]
en la creación del banco, para ver las cuentas solo permitelo desde la tabla el boton amarillo borralo porfa 

en la creacion de la cuenta del banco la fuente es un select y colocale el nombre de  "fuente de financiamiento" 
en la tabla de cuentas del banco, la columna `saldo` cámbiala a `saldo banco` añade también la columna sucursal y una columna de `estado` en la que indicaremos si la cuenta esta activa o inactiva y en lugar de borrar la cuenta que sea un boton de inactivar

para la parte de chequeras, tienes en la tabla el select de banco, añade el se sucursal  y el de cuentas para la búsqueda.
por ende si yo ya seleccione esos datos previamente, se podría dejar lo de datos del banco pero de manera informativa, como un label.

para la creacion de cheques no es necesario el select de estado ese borralo , el select de chequera no es necesario ya que se espera que lo seleccione previamente o que se llegue aqui desde la vista anteior donde estaban las chequeras.
En lo personal no le veo sentido el boton que dice  `cambiar estado` en la tabla, no se si tengas una razón para ello o si no eliminalo porfa

añade también de manera informativa el ultimo numero de cheque usado

**Comment by Jeisson005** [comment]
Se realiza lo siguiente:
- [ ] En la creación del banco, se borra el botón para ver las cuentas bancarias

- [ ] En la creación de la cuenta del banco, la fuente se cambia a una lista desplegable y se cambia el nombre del campo a "fuente de financiamiento"

En la tabla de cuentas del banco:
- [ ] La columna saldo se cambia a **saldo banco**
- [ ] Se añade la columna sucursal y una columna de estado en la que se indica si la cuenta esta activa o inactiva
- [ ] Se cambia el icono de borrar la cuenta por un icono que representa el cambio de estado

- [ ] En chequeras, se añade el filtro de sucursal y de cuentas para la búsqueda.

por ende si yo ya seleccione esos datos previamente, se podría dejar lo de datos del banco pero de manera informativa, como un label.

En la creación de cheques:
- [ ] Se elimina el select de estado, se cambia el listado desplegable de chequeras a un label donde solo se visualiza el número de la chequera.
- [ ] Se añade de manera informativa el ultimo numero de cheque usado.

Pendiente: En lo personal no le veo sentido el boton que dice cambiar estado en la tabla, no se si tengas una razón para ello o si no eliminalo porfa

**Comment by BOTOOM** [comment]
el boton de `cambiar estado` quitalo porfa

**Comment by BOTOOM** [comment]
- en la sección de giro por cheque , el consecutivo dejalo desactivado o borralo, eso lo generara el sistema automáticamente, la fecha también quilatala, el sistema la genera por defecto.
- puede que en los mockups aparezca diferente, pero en la explicación de maria claudia, en la sección de egreso el envió era una fecha, asi que es una fecha que se traerá, el consecutivo es el de la orden de pago, por ende se hace necesario lo siguiente:
  - justo arriba de egreso coloca un pequeño filtro donde se seleccione la vigencia y se ingrese un numero de orden de pago, luego de ello el sistema buscara los datos que aparecen en egreso
- en la parte de erogacion del giro esta bien que sea el banco para seleccionar, coloca el numero de la cuenta como un auto completado y el nombre de la cuenta se traerá según el numero de la cuenta, asi que no seria un seleccionable.
- también te falta mostrar el tipo de cuenta, solo seria un campo para mostrar y ya.
- en la parte de contabilización falta un campo ya sea select o autocompletado que permita seleccionar un concepto de contabilidad

**Comment by Jeisson005** [comment]
Se realizan los siguientes ajustes a los mockups, que se encuentran en el este [Enlace]
- [ ] En el listado de cheques se elimina el botón `cambiar estado`
En Giro de Cheques:
- [ ] Del paso 1 (Detalle), se elimina el campo de de `consecutivo`
- [ ] Del paso 1 (Detalle), se añaden los campos, `vigencia` y `Número de la orden de pago` para con éstos, traer los datos de egreso
- [ ] En el paso 2 (Erogación), se cambia el nombre de la cuenta a un label y el número de cuenta a un campo auto completado
- [ ] En el paso 2 (Erogación), se muestra como label el tipo de cuenta en el campo `Tipo de Cuenta`
- [ ] En el paso 3 (Contabilización), se agrega un campo de lista desplegable para el `concepto contable` junto al campo de _consecutivo_
