### ISSUE TITLE
mockups registro de ingresos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#38]
mockups de registro de ingresos

**Comment by Miranda13** [comment]
Se elabora el mockup para registrar:

- Ingresos del ICETEX
- Ingresos por código de barras
- Ingresos por inscripciones
- Ingresos por recaudo en línea
- Ingresos por aportes de la nación 
- Ingresos por aportes del distrito 

El link con permisos de edición: https://drive.google.com/file/d/1ZqQZxEQvwJ-_54AkJDccAoO2cbk_LMwX/view?usp=sharing
