### ISSUE TITLE
realizar mockups para giros

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#4]
en base a [parte grafica de giros](https://drive.google.com/drive/folders/1J_m9Uhu0QKOHWR_TIetwcvC_MrMF6pbZ?usp=sharing) y en los videos realizados del giros.

--- 
videos:
- [primera sesion](https://drive.google.com/drive/folders/1ngEpvmpFgt5ZxCBZFeYrXx_Axn37XIGv?usp=sharing)
- [segunda sesion](https://drive.google.com/drive/folders/1-CrweOYU9A0Dsf8WRKHApr7IKby5TuAq?usp=sharing)

---

***nota 1: se compartirá por correo documentos relacionados de desarrollos anteriores***
***nota 2: no se incluye bancos y cheques ya que eso ya esta a cargo de otra persona***

**Comment by Miranda13** [comment]
Se elabora el mockup para:
- Giros a proveedores
- Nómina
- Seguridad social
- Radicación de OP y RA 
- Reversar giros.

El link con permisos de edición: https://drive.google.com/file/d/19FA8ViAOgTsnQ11WtMqWbx9Lk1z36cSj/view?usp=sharing

**Comment by BOTOOM** [comment]
- en giros de RA y seguridad social desactiva la opcion de rango, eliminala, eso no se usara ya que no se define en los mockups su funcionamiento por ende en el buscador del siguiente paso solo se podra seleccionar una RA y ya con esa se trabaja.
- todas las secciones donde se selecciona al banco que generalmente es la erogacion , en todos los modulos, el banco debe ser un seleccionable y la cuenta del banco un auto completado.
- en la parte de la radicacion, añade las columnas de hash , pedis y demas, en esas columnas colocaremos un icono de :x:  o :heavy_check_mark:  y ya.
- en radicación para las aprobaciones ya tocaria hablar con jhon y maria c, con los 2 juntos para definir sii esa aprobación también se hace, por que anteriormente ya se hizo en central de cuentas, por que hacerla de nuevo?

**Comment by Miranda13** [comment]
Se realizan los siguientes ajustes:

- Se elimina en giros de RA y seguridad social la opción de rango.
- En erogación del giro de todas las secciones se pone un select para elegir el banco.
- En pago a proveedores, RA y seguridad social se agrega el botón para aprobar la contabilización que re dirige a un modal con pasos, y se agrega la nota de que debe estar aprobado antes de girar.
- Se añade en radiación de órdenes de pago hash, predis, pac y devuelta como un checkbox.
