### ISSUE TITLE
Socializacion Mockups de Ingresos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#41]
Es necesario socializar los mockups de ingresos

**Comment by Miranda13** [comment]
Se socializan los mockups de ingresos con @mcrubianot. Los ajustes a realizar son:

- [ ] Agregar el nombre del concepto.
- [ ] Mostrar la información del ingreso en el PDF.

**Comment by Miranda13** [comment]
Se socializa con el usuario y se hacen ajustes a mockups.
