### ISSUE TITLE
Mockups Declaracion de Retenciones

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#47]
Es necesario realizar los mockups de declaracion de retenciones

**Comment by Jeisson005** [comment]
El enlace de los mockups para [Declaración de Retenciones](https://drive.google.com/file/d/1mT_jIYeAJ8v9G3wxx8k3QV-GKDSHTmT_/view?usp=sharing)

**Comment by Jeisson005** [comment]
En la reunión de socialización con Maria Claudia, se tienen en cuenta los siguientes ajustes:

- [ ] En la vista de Detalle, agregar un campo para que los usuarios realicen la busqueda de las cuentas contables asociadas al tipo de declaración que se esta realizando.
- [ ] En la vista de Conciliación se establece un nuevo estado "Corregir" en caso de que la comparación entre los valores de la DIAN o SHD y los datos de la universidad no esten iguales, el usuario sera avisado y el proceso pasara a dicho estado hasta que se aclare o ajusten las diferencias.
- [ ] Se ajusta la vista de Conciliación para permitir al usuario hacer las agrupaciones que realizan en los formularios.
- [ ] Luego de la Conciliación, en conversaciones por el usuario por correo, la contabilización no se realiza en el módulo, se deberia redirigir al módulo de Giros. Por tanto el proceso termina en la conciliación y se le avisa al usuario que debe dirigirse a dicho modulo para continuar el proceso.
