### ISSUE TITLE
propuesta de cambios de avances

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#5]
en base a las historias de usuario , los sistemas actuales y los lineamientos actuales de la oficina proponer un modelo de datos ajustado al presentado y reconstruido en el [informe de avances](https://github.com/udistrital/financiera_documentacion/issues/183)

**Comment by NRDaza** [comment]
## Modelo de datos 

Se propone el siguiente modelo de datos, sujeto a recomendaciones y modificaciones

![New_Modelo_datos_Avance_Api_financiera-2021-01-22_13-10](https://user-images.githubusercontent.com/34488581/105528865-84180480-5cb3-11eb-96a3-dc8313b814de.png)


Link(vertabelo)
https://my.vertabelo.com/doc/GQ4xCb0AGYeTTx7E63gsbgPTlyFIUdIp

## Modificaciones

Respecto al anterior se propone los siguientes cambios:

- Se adicionan los lineamientos segun La Oas, se adicionan  los campos de fecha_creacion, fecha_modificacion, Activo a todas las tablas y renombra los campos que son llaves foraneas.
- Eliminar tablas: `etapa_avance`, `requisito_tipo_avance`, `solicitud_tipo_avance`
- Se adiciona campo `Link_norma `a la tabla `tipo_avance`
- Se adiciona tabla `especificaciones_avance`
- Se adiciona a la tabla `solicitud_avance` los campos: `tipo_documento`, `documento`, `area_funcional`, `cargo`, `fecha_evento`, `dependencia`, `facultad`, `proyecto curricular`
- Se elimina tablas `cuentas_especial`
- Se elimina tabla `tipo_documento_afectante `, pero se adiciona los campos `tipo_documento`, `documento `a la tabla `avance_legalizacion_tipo`
- Se adiciona tabla `consolidado_retencion`
- Se adiciona tabla `practica_academica`
- Se adiciona tabla `informacion_estudiante`

Presento dudas de como hacer la relaciona de las tablas de `practica_academica `con la tabla de `avance_legalizacion_tipo`, por el momento se deja asociada a la `tabla tipo_avance_legalizacion`

Algunas tablas no se quitaron ya que se encuentra que pueden tener relación con el tema de avances pero no se tiene claridad.
