### ISSUE TITLE
Socializacion Mockups Plan Anual de Caja

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#53]

**Comment by ManuelMurillo** [comment]
En la reunion del 08/03/2021 con Maria C se revisaron los mockups en los cuales se debe ajustar:

- [ ] Se puede tener la posibilidad de asociar mas de una fuente de financiamiento al rubro en la proyeccion
- [ ] La vista de rubros asociados se puede quitar
- [ ] Se debe ajustar el campo de rubro de la proyeccion para que se pueda seleccionar directamente
- [ ] antes de generar el reporte es necesario una vista para mostrar que los datos consultados de ingresos y gastos efectivamente concuerden, y en caso de alguna inconsistencia mostrar el error

**Comment by ManuelMurillo** [comment]
En la reunion del 17/08/2021 la analista Maria C aprueba los mockups de plan anual de caja

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
