### ISSUE TITLE
Socialización Mockups de Información Exógena

### ISSUE THREAD

**Issue by dmarcela09** [udistrital/tesoreria_cliente#60]
Realizar la socialización de los mockups #42 con la analista.

**Comment by dmarcela09** [comment]
En la reunión con la analista, se revisan los mockups del issue #42 de los cuales se plantean los siguientes ajustes:

- [ ] Agregar la opcion de "borrar" las consultas de información de la tabla.
- [ ] Unir la información en un documento final para la vista de Generación de Información Exógena.
- [ ] Mostrar el listado de los formatos prevalidador (autocompletado)
- [ ] Agregar la opción de "Aplicar cuantías menores" y el campo Valor de cuantía.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
