### ISSUE TITLE
Mockups Certificados de Retenciones

### ISSUE THREAD

**Issue by dmarcela09** [udistrital/tesoreria_cliente#64]
Es necesario realizar los mockups de Certificados de Retenciones luego de la capacitacion por parte de la analista.

**Comment by dmarcela09** [comment]
El enlace para los mockups de [Certificados de Retenciones](https://drive.google.com/file/d/1pRupg3CaHhXIS_y8ZfujmCScW2-Tqlue/view?usp=sharing)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
