### ISSUE TITLE
Vista Acreedores

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#67]

**Comment by ManuelMurillo** [comment]
Vistas Relacionadas para Acreedores:

Anulacion Cheque:

http://localhost:4200/#/pages/acreedores/anulacion-cheque/subir-archivo

http://localhost:4200/#/pages/acreedores/anulacion-cheque/tabla-anulacion

http://localhost:4200/#/pages/acreedores/anulacion-cheque/detalle-giro

http://localhost:4200/#/pages/acreedores/anulacion-cheque/anular-cheque

http://localhost:4200/#/pages/acreedores/anulacion-cheque/contabilizacion

Reactivacion de Pagos:

http://localhost:4200/#/pages/acreedores/reactivacion-pagos/solicitud-reactivacion-pago

http://localhost:4200/#/pages/acreedores/reactivacion-pagos/tabla-solicitudes

http://localhost:4200/#/pages/acreedores/reactivacion-pagos/respuesta-solicitud

Consulta Acreedores:

http://localhost:4200/#/pages/acreedores/consulta/tabla-consulta

http://localhost:4200/#/pages/acreedores/consulta/detalle

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
