### ISSUE TITLE
Vista Recaudo de matriculas Diferidas y Causacion cuentras por cobrar

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#68]

**Comment by ManuelMurillo** [comment]
Vistas Relacionadas con Recaudo de matriculas:

Reporte de Matriculas:

http://localhost:4200/#/pages/recaudo-matriculas/reporte-matriculas/tabla-general

http://localhost:4200/#/pages/recaudo-matriculas/reporte-matriculas/detalle-reporte

Consulta de Matriculas:

http://localhost:4200/#/pages/recaudo-matriculas/consulta-matriculas/consulta-general

http://localhost:4200/#/pages/recaudo-matriculas/consulta-matriculas/tabla-general

http://localhost:4200/#/pages/recaudo-matriculas/consulta-matriculas/contabilizacion

Reporte de Mora:

http://localhost:4200/#/pages/recaudo-matriculas/reporte-mora/consulta-general

http://localhost:4200/#/pages/recaudo-matriculas/reporte-mora/tabla-general

Control de Mora:

http://localhost:4200/#/pages/recaudo-matriculas/control-mora/tabla-general

http://localhost:4200/#/pages/recaudo-matriculas/control-mora/detalle-reporte

http://localhost:4200/#/pages/recaudo-matriculas/control-mora/contabilizacion

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
