### ISSUE TITLE
Vista Plan Anual de Caja

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#69]

**Comment by ManuelMurillo** [comment]
Direcciones de vistas relacionadas:

Proyeccion:

http://localhost:4200/#/pages/plan-anual-caja/proyeccion/tabla-solicitudes

http://localhost:4200/#/pages/plan-anual-caja/proyeccion/form-rubro-pac

http://localhost:4200/#/pages/plan-anual-caja/proyeccion/tabla-proyeccion

Aprobacion:

http://localhost:4200/#/pages/plan-anual-caja/aprobacion/aprobar-pac

Seguiniento:

http://localhost:4200/#/pages/plan-anual-caja/seguimiento/seguimiento-pac

Reporte:

http://localhost:4200/#/pages/plan-anual-caja/reporte/reporte-pac

http://localhost:4200/#/pages/plan-anual-caja/reporte/revision-reporte-pac

http://localhost:4200/#/pages/plan-anual-caja/reporte/revision-reporte-pac?valid=true

http://localhost:4200/#/pages/plan-anual-caja/reporte/tabla-reporte-pac

Cierre:

http://localhost:4200/#/pages/plan-anual-caja/cierre/cierre-pac

http://localhost:4200/#/pages/plan-anual-caja/cierre/tabla-cierre-pac

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
