### ISSUE TITLE
Socializacion Mockups Acreedores

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#76]

**Comment by ManuelMurillo** [comment]
En la reunion del 26/03/2021 con la analista Maria C se agregaron los siguientes ajustes:

- [ ] En la vista de anulacion de cheques hay que agregar una vista para cotejar los reportes del banco con los datos del sistema y asi extraer la informacion de los cheques no cobrados y efectivos no reclamados

- [ ] para la solicitud de reactivacion es necesario agregar un modal de consulta de orden de pago para observar si efectivamente es posible aprobar la reactivacion

**Comment by ManuelMurillo** [comment]
En la reunion del 30/03/2021 la analista Maria C da el aval para la creacion de las vistas asociadas

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
