### ISSUE TITLE
Socializacion Mockups Recaudo Matriculas Diferidas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#77]

**Comment by ManuelMurillo** [comment]
En la reunion del 26/03/2021 la analista Maria c realiza las siguientes observaciones:

- [ ]  Para el control de los recaudos es necesario revisar las actas 052, 056, y 058

**Comment by ManuelMurillo** [comment]
En la reunion del 30/03/2021 la analista Maria C da el aval para la creacion de las vistas asociadas

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
