### ISSUE TITLE
realizar maquetación de requisitos del sistema de avances

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#8]
con base en los mockups #1 elaborar la vista de requisitos de avances

**Comment by Jeisson005** [comment]
**Se generan las siguientes vistas:**

- http://localhost:4200/#/pages/avances/requisitosavances/lista
![image](https://user-images.githubusercontent.com/24659130/106532096-894c2f00-64bd-11eb-913d-76b489084340.png)

- http://localhost:4200/#/pages/avances/requisitosavances/crear
![image](https://user-images.githubusercontent.com/24659130/106532136-9d902c00-64bd-11eb-93e9-0ba2510ed871.png)

- http://localhost:4200/#/pages/avances/requisitosavances/editar
![image](https://user-images.githubusercontent.com/24659130/106532165-a97bee00-64bd-11eb-9b08-1641596a2813.png)

**Nota:** El mismo componente se reutiliza para la generación de las últimas dos
