### ISSUE TITLE
Vistas y Modelos

### ISSUE THREAD

**Issue by Jeisson005** [udistrital/tesoreria_cliente#86]
Conforme al compromiso, se listan las actividades por realizar 

1. GFR-PR-006 Trámites de pago

- [x] Modelos de datos
- [x] Vistas

2. GFR-PR-012 Avances
- [x] Modelos de datos
- [x] Vistas
3. GFR-PR-015 Declaración de retenciones
- [x] Modelos de datos
- [x] Vistas
4. GFR-PR-016 Certificados de recaudo y reintegro
- [x] Modelos de datos
- [x] Vistas

**Comment by Jeisson005** [comment]
**GFR-PR-006 Trámites de pago**
Por trámites de pago se entiende todo el procedimiento referente al subsistema central de cuentas.
El modelo de datos que se encuentra propuesto hasta el momento es el siguiente:
[Modelo de datos](https://github.com/udistrital/financiera_documentacion/blob/master/central_cuentas/orden_pago/orden_pafo.md)
El repositorio con el código de backend es el siguiente:
[central_cuentas_crud](https://github.com/udistrital/central_cuentas_crud)
Las vistas se encuentran el repositorio:
[central_cuentas_cliente](https://github.com/udistrital/central_cuentas_cliente)

**Comment by Jeisson005** [comment]
**GFR-PR-012 Avances**
El modelo de datos que se encuentra propuesto hasta el momento es el siguiente:
[Modelo de datos](https://github.com/udistrital/avances_crud/blob/master/database/modelobd.png)
El repositorio con el código de backend es el siguiente:
[avances_crud](https://github.com/udistrital/avances_crud)
Las vistas se encuentran el repositorio:
[avances_cliente](https://github.com/udistrital/avances_cliente)

**Comment by Jeisson005** [comment]
**GFR-PR-015 Declaración de retenciones**

**Comment by Jeisson005** [comment]
**GFR-PR-016 Certificados de recaudo y reintegro**
Las vistas realizadas se encuentran en el siguiente repositorio:
[tesoreria_cliente](https://github.com/udistrital/tesoreria_cliente)
Para el caso del modelo de datos, no se requiere uno nuevo, por lo que se utilizan las siguientes APIs:

- terceros_crud, para obtener los datos del solicitante
- sistema de gestión académica, para obtener las matrículas pagadas
- plan_cuentas_mongo_crud, para obtener la vigencia
- movimientos_contables_crud, para obtener los movimientos correspondientes al pago de matrícula
- parametros_crud
- solicitudes_crud

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
