### ISSUE TITLE
Entregables

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/tesoreria_cliente#87]
Se listan los siguientes entregables:

- [x] Modelo Datos PAC
- [x] Modelo Datos Acreedores
- [x] Modelo Datos Recaudo Matriculas Diferidas

**Comment by ManuelMurillo** [comment]
Modelo de Datos PAC

https://drive.google.com/file/d/1cAQ9Guu1ztYTRo7d12zjoSHmD736-uIE/view?usp=sharing

![Captura de pantalla de 2021-04-26 00-50-08](https://user-images.githubusercontent.com/29108085/116034876-a52d2000-a629-11eb-8563-e4bd58bfb43d.png)

**Comment by ManuelMurillo** [comment]
Modelo Recaudo Matriculas Diferidas

https://drive.google.com/file/d/1vO_563iKwpA5NwbpJm0zo3PsaqQH0_lM/view?usp=sharing

![Captura de pantalla de 2021-04-26 01-09-41](https://user-images.githubusercontent.com/29108085/116036326-1b328680-a62c-11eb-8025-aa0e10afce96.png)

**Comment by ManuelMurillo** [comment]
Modelo Acreedores

https://drive.google.com/file/d/1KYcBAMVMvNbw1hS_hmEfTkTtOt9N5QlQ/view?usp=sharing

![Captura de pantalla de 2021-04-26 02-19-11](https://user-images.githubusercontent.com/29108085/116044024-0955e100-a636-11eb-968b-5c0ed0f8c20f.png)

Tabla: acreedores
| Nombre            | Descripcion |
|-------------------|-------------|
| id | Llave Primaria |
| activo | Registro activo |
| fecha_creacion | Fecha de Creacion |
| fecha_modificacion | Fecha de Actualizacion |
| tercero_id | tercero / acreedor asociado |
| orden_pago_id | orden de pago asociada |
| giro_id | giro asociado |

Tabla: solicitud_reactivacion
| Nombre            | Descripcion |
|-------------------|-------------|
| id | Llave Primaria |
| activo | Registro activo |
| fecha_creacion | Fecha de Creacion |
| fecha_modificacion | Fecha de Actualizacion |
| descripcion | descripcion de la solicitud |
| nombre | nombre del solicitante |
| apellido | apellidos del solicitante |
| codigo | codigo asociado del solicitante |
| tipo_documento | tipo de documento |
| numero_documento | numero de documento |
| aprobado | bandera para saber si esta aprobadala solicitud |

Tabla: soportes
| Nombre            | Descripcion |
|-------------------|-------------|
| id | Llave Primaria |
| activo | Registro activo |
| fecha_creacion | Fecha de Creacion |
| fecha_modificacion | Fecha de Actualizacion |
| soporte_id | soporte asociado |

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
