### ISSUE TITLE
vista de especificaciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/tesoreria_cliente#9]
con base en los mockups #1 se requiere realizar la vista de especificaciones

**Comment by Jeisson005** [comment]
**Se generan las siguientes vistas:**
http://localhost:4200/#/pages/avances/especificacionesavances/lista
![image](https://user-images.githubusercontent.com/24659130/106700247-72d3cf80-65b2-11eb-81b3-cc38e6e3e5cf.png)

http://localhost:4200/#/pages/avances/especificacionesavances/crear
![image](https://user-images.githubusercontent.com/24659130/106700268-7ebf9180-65b2-11eb-8b6f-601716e23b88.png)

http://localhost:4200/#/pages/avances/especificacionesavances/editar
![image](https://user-images.githubusercontent.com/24659130/106700287-867f3600-65b2-11eb-8c5a-8b55115c4063.png)
