### ISSUE TITLE
Crear vista de ingresos

### ISSUE THREAD

**Issue by Miranda13** [udistrital/tesoreria_cliente#99]
Se requiere crear vista de ingresos con base a los mockups.

**Comment by mcrubianot** [comment]
Los mockups de este desarrollo fueron aprobados por el usuario en el acta No. 070 `https://drive.google.com/file/d/1e0a8K25OhNqxv7OF9SbTmICJtYlLdHlQ/view?usp=sharing` del 2020

En en cliente de Tesorería no hay ningún desarrollo relacionado.

**Comment by AlexFBP** [comment]
Vale @mcrubianot , hay un despliegue pendiente que incluye lo desarrollado para este Issue, que no se ha desplegado aún al ambiente de pruebas por razón de unos ajustes (menores) que se están haciendo (#107 ) y que ya se están terminando de hacer. Te avisaré tan pronto esté disponible

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
